const data = [
  {
    id: 1,
    name: "Pilot Coffee Roasters",
    neighbourhood: "Ossington",
    address: "117 Ossington Ave, Toronto, ON M6J 2Z2",
    features: ["wifi", "quiet", "cozy"],
    rating: 4.3,
    vibe: "Industrial-chic specialty roaster. Great atmosphere for focused work.",
    mapUrl: "https://maps.app.goo.gl/96fy13cYqqMqfAxV6",
    image: {
      src: "images/pilot-coffee.png",
      alt: "Pilot Coffee Roasters industrial interior with high ceilings and espresso bar on Ossington",
    },
  },
  {
    id: 2,
    name: "Dineen Coffee Co.",
    neighbourhood: "Financial District",
    address: "140 Yonge St, Toronto, ON M5C 1X6",
    features: ["wifi", "outlets", "quiet"],
    rating: 4.3,
    vibe: "Elegant historic building with a dedicated workspace at the back. 2-hour WiFi limit.",
    mapUrl: "https://maps.app.goo.gl/JPbWPvUZPvXT3jX66",
    image: {
      src: "images/dineen-coffee.png",
      alt: "Dineen Coffee Co. elegant interior inside a historic Yonge Street building",
    },
  },
  {
    id: 3,
    name: "Jimmy's Coffee",
    neighbourhood: "Kensington Market",
    address: "191 Baldwin St, Toronto, ON M5T 1M1",
    features: ["wifi", "outlets", "dog friendly"],
    rating: 4.4,
    vibe: "Laid-back indie spot with a loyal local crowd. Best for light work sessions.",
    mapUrl: "https://maps.app.goo.gl/6ovq5755wByLqTjH7",
    image: {
      src: "images/jimmys-coffee.png",
      alt: "Jimmy's Coffee cozy interior with eclectic decor in Kensington Market",
    },
  },
  {
    id: 4,
    name: "Boxcar Social",
    neighbourhood: "Summerhill",
    address: "1208 Yonge St, Toronto, ON M4T 1W1",
    features: ["wifi", "outlets", "coffee and beer"],
    rating: 4.3,
    vibe: "Café-bar hybrid with upstairs nooks. Plugs everywhere, great for long sessions.",
    mapUrl: "https://maps.app.goo.gl/DTjVzdX8CW8RSxHF6",
    image: {
      src: "images/boxcar-social.png",
      alt: "Boxcar Social rustic interior blending café and bar elements in Summerhill",
    },
  },
  {
    id: 5,
    name: "Dark Horse Espresso Bar",
    neighbourhood: "Leslieville",
    address: "630 Queen St E, Toronto, ON M4M 1G3",
    features: ["wifi", "spacious", "dog friendly"],
    rating: 4.2,
    vibe: "Cool Riverside spot with unique atmosphere, curated shop, and vegan options.",
    mapUrl: "https://maps.app.goo.gl/adiGB1cCmwqygshUA",
    image: {
      src: "images/dark-horse.png",
      alt: "Dark Horse Espresso Bar warm and inviting interior on Queen Street East",
    },
  },
  {
    id: 6,
    name: "Rooster Coffee House",
    neighbourhood: "Broadview",
    address: "479 Broadview Ave, Toronto, ON M4K 2N4",
    features: ["wifi", "quiet", "spacious"],
    rating: 4.6,
    vibe: "City skyline views, tons of natural light, and one of the best matcha lattes in Toronto.",
    mapUrl: "https://maps.app.goo.gl/ZGMESJdJnPBpgZnv6",
    image: {
      src: "images/rooster-coffee.png",
      alt: "Rooster Coffee House bright interior with city skyline views on Broadview Ave",
    },
  },
];
